WebApp-Site vendas/Controllers/EncomendasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Api.Data;
using Projeto_CLOUD_45_2021.Models;
using Microsoft.AspNetCore.Authorization;

namespace WebApp_Site_vendas.Controllers
{
    public class EncomendasController : Controller
    {
        private readonly DataBaseContext _context;

        public EncomendasController(DataBaseContext context)
        {
            _context = context;
        }

         [Authorize]
        public async Task<IActionResult> MinhasEncomendas()
        {
            var utilizador = _context.Utilizadores.FirstOrDefault(e => e.Email == User.Identity.Name);
            var dataBaseContext = _context.Encomendas.Include(e => e.Produto).Include(e => e.Utilizador).Where(c => c.UtilizadorId == utilizador.UtilizadorId);
            return View(await dataBaseContext.ToListAsync());
        }


        [Authorize]
        public async Task<IActionResult> ConfirmacaoEncomenda()
        {
            return View();
        }

       
    }
}

WebApp-Site vendas/Controllers/UtilizadoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Api.Data;
using Projeto_CLOUD_45_2021.Models;
using System.Net.Http;
using System.Net.Http.Json;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication;

namespace WebApp_Site_vendas.Controllers
{
    public class UtilizadoresController : Controller
    {
        private readonly DataBaseContext _context;
        private readonly UserManager<IdentityUser> userManager;
        private readonly SignInManager<IdentityUser> signInManager;

        public UtilizadoresController(DataBaseContext context, UserManager<IdentityUser> userManager,
            SignInManager<IdentityUser> signInManager)
        {
            _context = context;
            this.userManager = userManager;
            this.signInManager = signInManager;
        }

       
        public ActionResult Create()
        {
            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UtilizadorId,Nome,Contribuinte,DataNascimento,Telefone,Email,DataRegisto,Password,Morada,Numero,Andar,Localidade,CodigoPostal")] Utilizador utilizador)
        {
            if (ModelState.IsValid)
            {
                var check = _context.Utilizadores.FirstOrDefault(e => e.Email == utilizador.Email);

                if (check == null)
                {
                    _context.Add(utilizador);
                    await _context.SaveChangesAsync();

                    var userIdentity = new IdentityUser
                    {
                        UserName = utilizador.Email,
                        Email = utilizador.Email
                    };
                    var result = await userManager.CreateAsync(userIdentity, utilizador.Password);                    

                    if (result.Succeeded)
                    {
                        await signInManager.SignInAsync(userIdentity, isPersistent: false);
                        return RedirectToAction("MinhaConta", utilizador);
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "Dados inválidos!");
                    }
                }

                else
                {
                    ModelState.AddModelError(string.Empty, "Email já registado, por favor registe um novo email!");
                }
            }

            return View(utilizador);
        }


        
        [Authorize]
        public async Task<IActionResult> Edit()
        {
            var user = _context.Utilizadores.FirstOrDefault(e => e.Email == User.Identity.Name);
            var userId = user.UtilizadorId;

            var utilizador = await _context.Utilizadores.FindAsync(userId);

            if (utilizador == null)
            {
                return NotFound();
            }

            return View(utilizador);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UtilizadorId,Nome,Contribuinte,DataNascimento,Telefone,Email,DataRegisto,Password,Morada,Numero,Andar,Localidade,CodigoPostal")] Utilizador utilizador)
        {
            if (id != utilizador.UtilizadorId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(utilizador);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UtilizadorExists(utilizador.UtilizadorId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                    
                }

                return RedirectToAction("MinhaConta", utilizador);
            }

            return View(utilizador);
        }

        [HttpGet]
        public async Task<IActionResult> Login()
        {

            return View();
                    
        }

        [HttpPost]
        public async Task<IActionResult> Login(Utilizador utilizador)
        {
            if (ModelState.IsValid)
            {
                var result = await signInManager.PasswordSignInAsync(
                    utilizador.Email, utilizador.Password, false, false);
                if (result.Succeeded)
                {
                    return RedirectToAction("MinhaConta", utilizador);
                }
                ModelState.AddModelError(string.Empty, "Login Inválido");
            }
            return View(utilizador);
        }

        public async Task<IActionResult> Logout()
        {
            await signInManager.SignOutAsync();
            return RedirectToAction("index", "home");
        }

        
        [Authorize]
        public IActionResult MinhaConta(Utilizador utilizador)
        {
            var user = _context.Utilizadores.FirstOrDefault(e => e.Email == User.Identity.Name);

            return View(user);
        }

       
        private bool UtilizadorExists(int id)
        {
            return _context.Utilizadores.Any(e => e.UtilizadorId == id);
        }

    }
}

WebApp-Site vendas/Views/Encomendas/ConfirmacaoEncomenda.cshtml
@{
    ViewData["Title"] = "Confirmacao Encomenda";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<div class="container text-center">
    <h2>Obrigado por comprar connosco!</h2><br />  
    <h3>Encomenda recebida!</h3>
    <p>Enviamos para o seu email uma confirmação de seu pedido!</p>
    <p>
        Atenciosamente,<br />
        Equipa Mundo das Plantas.
    </p>
    <p>
        <a class="btn btn-success btn-lg" asp-controller="Home" asp-action="Index">Voltar à pagina principal</a>
    </p>
</div>

WebApp-Site vendas/Views/Encomendas/MinhasEncomendas.cshtml
@model IEnumerable<Projeto_CLOUD_45_2021.Models.Encomenda>


@{
    ViewData["Title"] = "Minha Encomendas";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<div class="container">
    <div class="row gx-3">
        <div class="col-4">
            <div class="list-group">
                <a asp-controller="Utilizadores" asp-action="Edit" asp-route-id="" class="list-group-item list-group-item-action ">
                    <i class="fas fa-user"></i> Dados Pessoais
                </a>
                <a asp-controller="Encomendas" asp-action="MinhasEncomendas" class="list-group-item list-group-item-action bg-success text-light">
                    <i class="fas fa-truck"></i> Encomendas
                </a>
                <a asp-controller="Utilizadores" asp-action="Logout" class="list-group-item list-group-item-action">
                    <i class="fas fa-door-open"></i> Sair
                </a>
            </div>
        </div>
        <div class="col-8">
            <h2>Minhas Encomendas: </h2>
            <hr />
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            Encomenda nº:
                        </th>
                        <th>
                            Data:
                        </th>                       
                        <th>
                            Valor:
                        </th>                       
                        <th>
                            Produtos:
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                               @Html.DisplayFor(modelItem => item.EncomendaId)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.DataEncomenda)
                            </td>                            
                            <td>
                                € @Html.DisplayFor(modelItem => item.ValorTotal)
                            </td>                            
                            <td>
                                @Html.DisplayFor(modelItem => item.Produto.NomeComum)
                            </td>                            
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>