WebApp-Site vendas/Controllers/ComunidadeController.cs
using Azure.Storage.Blobs;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace WebApp_Site_vendas.Controllers
{
    public class ComunidadeController : Controller
    {
        // GET: ComunidadeController
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Desafio(string nome)
        {
            string nomeplanta = "verbena";

            if (nome == nomeplanta)
            {
                return View("Acertou");
            }
            else
            {
                return View("Errou");
            }
           
        }


        [HttpPost]
        public ActionResult Upload(IFormFile file)
        {
            BlobServiceClient blobServiceClient = new BlobServiceClient("DefaultEndpointsProtocol=https;AccountName=asprojeto;AccountKey=a0B+PPewtIG4+ngBo/4uXdEnNq/RGCvVESJat3kcNOdmYTydATc8ik9Y7oumfAJOEJXvfyF5lP3zjOGROOPguA==;EndpointSuffix=core.windows.net");

            string containername = "amandaimages";

            var blobContainers = blobServiceClient.GetBlobContainers();

            var s = from bc in blobContainers where bc.Name.Equals(containername) select bc;

            BlobContainerClient blobContainerClient = null;

            if (s != null)
            {
                blobContainerClient = blobServiceClient.GetBlobContainerClient(containername);
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Impossível fazer upload no momento!");
            }


            
            var filename = Path.GetFileName(file.FileName);
            BlobClient blobClient = blobContainerClient.GetBlobClient("clienteimage" + filename);
            
            using (Stream filenew = file.OpenReadStream())
            {
                blobClient.Upload(filenew);
            }

            var url = blobClient.Uri.AbsoluteUri;

            ViewBag.Foto = url;

            return View("Index");

        }
        
    }
}

WebApp-Site vendas/Controllers/ProdutosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Api.Data;
using Projeto_CLOUD_45_2021.Models;
using WebApp_Site_vendas.Models;
using Newtonsoft.Json;
using WebApp_Site_vendas.Data;
using System.Collections;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Azure.Storage.Queues;
using Azure.Storage.Queues.Models;
using Microsoft.IdentityModel.Protocols;
using System.Configuration;

namespace WebApp_Site_vendas.Controllers
{
    public class ProdutosController : Controller
    {
        private readonly DataBaseContext _context;
        private readonly DataBaseCarrinhoContext _carrinhocontext;
        private readonly UserManager<IdentityUser> userManager;
        private readonly SignInManager<IdentityUser> signInManager;

        public ProdutosController(DataBaseContext context, DataBaseCarrinhoContext carrinhoContext, UserManager<IdentityUser> userManager,
            SignInManager<IdentityUser> signInManager)
        {
            _context = context;
            _carrinhocontext = carrinhoContext;
            this.userManager = userManager;
            this.signInManager = signInManager;
        }

        // GET: Produtos

        public async Task<IActionResult> Index(int? id)
        {
            var dataBaseContext = _context.Produtos.Include(p => p.Categoria).Where(c => c.CategoriaId == id);
            return View(await dataBaseContext.ToListAsync());
        }

        // GET: Produtos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produto = await _context.Produtos
                .Include(p => p.Categoria)
                .FirstOrDefaultAsync(m => m.ProdutoId == id);
            if (produto == null)
            {
                return NotFound();
            }

            return View(produto);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> AddCarrinho(int? id)
        {
            var itens = _context.Produtos.Include(c => c.Categoria).FirstOrDefault(m => m.ProdutoId == id);
            var utilizador = _context.Utilizadores.FirstOrDefault(e => e.Email == User.Identity.Name);
            var cart = _carrinhocontext.Carrinho.FirstOrDefault(c => c.ProdutoId == id);


            if (cart == null)
            {
                cart = new CarrinhoCompras();
                {
                    cart.CarrinhoId = Guid.NewGuid();
                    cart.ProdutoId = itens.ProdutoId;
                    cart.ClienteId = utilizador.UtilizadorId;
                    cart.Foto = itens.Foto;
                    cart.Quantidade = 1;
                    cart.ValorTotal = itens.Preco;
                    cart.PrecoUnit = itens.Preco;
                    cart.Nome = itens.NomeComum;
                }

                _carrinhocontext.Add(cart);
            }
            else
            {
                cart.Quantidade++;
                cart.ValorTotal = cart.Quantidade * cart.PrecoUnit;
            }

            _carrinhocontext.SaveChanges();

            var itensUtilizador = _carrinhocontext.Carrinho.Where(c => c.ClienteId == utilizador.UtilizadorId);
            ViewBag.CarrinhoTotal = itensUtilizador.Sum(s => s.ValorTotal).ToString();

            return View(itensUtilizador.ToList());

        }

        [Authorize]
        public async Task<IActionResult> AddItemCarrinho(int? id)
        {
            var utilizador = _context.Utilizadores.FirstOrDefault(e => e.Email == User.Identity.Name);
            var itensUtilizador = _carrinhocontext.Carrinho.Where(c => c.ClienteId == utilizador.UtilizadorId);
            var cart = _carrinhocontext.Carrinho.FirstOrDefault(c => c.ProdutoId == id);

            try
            {
                cart.Quantidade++;
                cart.ValorTotal = cart.Quantidade * cart.PrecoUnit;
                _carrinhocontext.SaveChanges();
            }
            catch (Exception)
            {

                throw;
            }

            ViewBag.CarrinhoTotal = itensUtilizador.Sum(s => s.ValorTotal).ToString();

            return View("AddCarrinho", itensUtilizador.ToList());
        }

        [Authorize]
        public async Task<IActionResult> DiminuirItemCarrinho(int? id)
        {
            var utilizador = _context.Utilizadores.FirstOrDefault(e => e.Email == User.Identity.Name);
            var itensUtilizador = _carrinhocontext.Carrinho.Where(c => c.ClienteId == utilizador.UtilizadorId);
            var cart = _carrinhocontext.Carrinho.FirstOrDefault(c => c.ProdutoId == id);

            try
            {
                cart.Quantidade--;
                cart.ValorTotal = cart.Quantidade * cart.PrecoUnit;
                _carrinhocontext.SaveChanges();

                if (cart.Quantidade < 1)
                {
                    await RemoverItemCarrinho(cart.ProdutoId);
                }

            }
            catch (Exception)
            {

                throw;
            }

            ViewBag.CarrinhoTotal = itensUtilizador.Sum(s => s.ValorTotal).ToString();

            return View("AddCarrinho", itensUtilizador.ToList());
        }

        [Authorize]
        public async Task<IActionResult> RemoverItemCarrinho(int? id)
        {
            var utilizador = _context.Utilizadores.FirstOrDefault(e => e.Email == User.Identity.Name);
            var itensUtilizador = _carrinhocontext.Carrinho.Where(c => c.ClienteId == utilizador.UtilizadorId);
            var cartItem = _carrinhocontext.Carrinho.FirstOrDefault(c => c.ProdutoId == id);

            try
            {
                _carrinhocontext.Remove(cartItem);
                _carrinhocontext.SaveChanges();
            }
            catch (Exception)
            {

                throw;
            }

            ViewBag.CarrinhoTotal = itensUtilizador.Sum(s => s.ValorTotal).ToString();

            return View("AddCarrinho", itensUtilizador.ToList());
        }

        [Authorize]
        public async Task<IActionResult> MeuCarrinho()
        {
            var utilizador = _context.Utilizadores.FirstOrDefault(e => e.Email == User.Identity.Name);
            var itensUtilizador = _carrinhocontext.Carrinho.Where(c => c.ClienteId == utilizador.UtilizadorId);

            ViewBag.CarrinhoTotal = itensUtilizador.Sum(s => s.ValorTotal).ToString();
            return View("MeuCarrinho", itensUtilizador.ToList());
        }


        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Encomendar()
        {
            var utilizador = _context.Utilizadores.FirstOrDefault(e => e.Email == User.Identity.Name);
            var carrinhoUtilizador = _carrinhocontext.Carrinho.Where(c => c.ClienteId == utilizador.UtilizadorId);
            var carrinho = carrinhoUtilizador.FirstOrDefault(); //corrigir, só está a apagar o primeiro, obviamente!

            List<CarrinhoCompras> listaItens = carrinhoUtilizador.ToList();
            Item_Encomenda novoItemEncomenda = new Item_Encomenda();

            List<Item_Encomenda> itensEncomenda = new List<Item_Encomenda>();

            foreach (var item in listaItens)
            {
                novoItemEncomenda.ProdutoId = item.ProdutoId;
                novoItemEncomenda.Quantidade = item.Quantidade;
                novoItemEncomenda.Preco = item.PrecoUnit;

                _context.Add(novoItemEncomenda);
                itensEncomenda.Add(novoItemEncomenda);
            }
            
            Encomenda novaEnc = new Encomenda();
            novaEnc.DataEncomenda = DateTime.Now;
            novaEnc.UtilizadorId = utilizador.UtilizadorId;
            novaEnc.ValorTotal = itensEncomenda.Sum(p => p.Preco * p.Quantidade); //corrigir!
            novaEnc.UtilizadorId = utilizador.UtilizadorId;
            novaEnc.ProdutoId = novoItemEncomenda.ProdutoId;
            novaEnc.Itens_Encomenda = itensEncomenda;
            _context.Add(novaEnc);

            _context.SaveChanges();


            _carrinhocontext.Remove(carrinho);
            _carrinhocontext.SaveChanges();

            return RedirectToAction("ConfirmacaoEncomenda", "Encomendas");

        }

    }
}

WebApp-Site vendas/Controllers/UtilizadoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Api.Data;
using Projeto_CLOUD_45_2021.Models;
using System.Net.Http;
using System.Net.Http.Json;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication;

namespace WebApp_Site_vendas.Controllers
{
    public class UtilizadoresController : Controller
    {
        private readonly DataBaseContext _context;
        private readonly UserManager<IdentityUser> userManager;
        private readonly SignInManager<IdentityUser> signInManager;

        public UtilizadoresController(DataBaseContext context, UserManager<IdentityUser> userManager,
            SignInManager<IdentityUser> signInManager)
        {
            _context = context;
            this.userManager = userManager;
            this.signInManager = signInManager;
        }

       
        public ActionResult Create()
        {
            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UtilizadorId,Nome,Contribuinte,DataNascimento,Telefone,Email,DataRegisto,Password,Morada,Numero,Andar,Localidade,CodigoPostal")] Utilizador utilizador)
        {
            if (ModelState.IsValid)
            {
                var check = _context.Utilizadores.FirstOrDefault(e => e.Email == utilizador.Email);

                if (check == null)
                {
                    _context.Add(utilizador);
                    await _context.SaveChangesAsync();

                    var userIdentity = new IdentityUser
                    {
                        UserName = utilizador.Email,
                        Email = utilizador.Email
                    };
                    var result = await userManager.CreateAsync(userIdentity, utilizador.Password);                    

                    if (result.Succeeded)
                    {
                        await signInManager.SignInAsync(userIdentity, isPersistent: false);
                        return RedirectToAction("MinhaConta", utilizador);
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "Dados inválidos!");
                    }
                }

                else
                {
                    ModelState.AddModelError(string.Empty, "Email já registado, por favor registe um novo email!");
                }
            }

            return View(utilizador);
        }


        
        [Authorize]
        public async Task<IActionResult> Edit()
        {
            var user = _context.Utilizadores.FirstOrDefault(e => e.Email == User.Identity.Name);
            var userId = user.UtilizadorId;

            var utilizador = await _context.Utilizadores.FindAsync(userId);

            if (utilizador == null)
            {
                return NotFound();
            }

            return View(utilizador);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UtilizadorId,Nome,Contribuinte,DataNascimento,Telefone,Email,DataRegisto,Password,Morada,Numero,Andar,Localidade,CodigoPostal")] Utilizador utilizador)
        {
            if (id != utilizador.UtilizadorId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(utilizador);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UtilizadorExists(utilizador.UtilizadorId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                    
                }

                return RedirectToAction("MinhaConta", utilizador);
            }

            return View(utilizador);
        }

        [HttpGet]
        public async Task<IActionResult> Login()
        {

            return View();
                    
        }

        [HttpPost]
        public async Task<IActionResult> Login(Utilizador utilizador)
        {
            if (ModelState.IsValid)
            {
                var result = await signInManager.PasswordSignInAsync(
                    utilizador.Email, utilizador.Password, false, false);
                if (result.Succeeded)
                {
                    return RedirectToAction("MinhaConta", utilizador);
                }
                ModelState.AddModelError(string.Empty, "Login Inválido");
            }
            return View(utilizador);
        }

        public async Task<IActionResult> Logout()
        {
            await signInManager.SignOutAsync();
            return RedirectToAction("index", "home");
        }

        
        [Authorize]
        public IActionResult MinhaConta(Utilizador utilizador)
        {
            var user = _context.Utilizadores.FirstOrDefault(e => e.Email == User.Identity.Name);

            return View(user);
        }

       
        private bool UtilizadorExists(int id)
        {
            return _context.Utilizadores.Any(e => e.UtilizadorId == id);
        }

    }
}

WebApp-Site vendas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mundo das Plantas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" />
    <link href="~/css/site.css" rel="stylesheet" />

</head>
<body>
    @using Microsoft.AspNetCore.Identity

    @inject SignInManager<IdentityUser> SignInManager
    @inject UserManager<IdentityUser> UserManager
    <div class="d-flex flex-column wrapper">
        <header>
            <nav class="navbar navbar-expand-lg navbar-dark bg-success border-bottom shadow-sm-mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><b>Mundo das Plantas</b></a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-white" href="https://localhost:44370/">Área restrita</a>
                            </li>
                            <li class="nav-item">
                                <a asp-area="" asp-controller="Comunidade" asp-action="Index" class="nav-link text-white">Comunidade</a>
                            </li>
                        </ul>
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <div class="align-self-end">
                                <ul class="navbar-nav">
                                    <li class="nav-item">
                                        <a asp-area="" asp-controller="Utilizadores" asp-action="Logout" class="nav-link text-white">Logout</a>
                                    </li>
                                    <li class="nav-item">
                                        <a asp-area="" asp-controller="Utilizadores" asp-action="MinhaConta" class="nav-link text-white">Minha Conta</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="fas fa-shopping-cart" style="font-size:30px; color: white;" asp-controller="Produtos" asp-action="MeuCarrinho"></a>
                                    </li>
                                </ul>
                            </div>
                        }
                        else
                        {
                            <div class="align-self-end">
                                <ul class="navbar-nav">
                                    <li class="nav-item">
                                        <a asp-area="" asp-controller="Utilizadores" asp-action="Create" class="nav-link text-white">Registar</a>
                                    </li>
                                    <li class="nav-item">
                                        <a asp-area="" asp-controller="Utilizadores" asp-action="Login" class="nav-link text-white">Login</a>
                                    </li>
                                </ul>
                            </div>
                        }
                    </div>
                </div>
            </nav>
        </header>

        <main class="flex-fill">

            @RenderBody()

        </main>


        <footer class="border-top bg-success text-white">
            <div class="container">
                <div class="row py-3">
                    <div class="col-12 col-md-4 text-center">
                        &copy; 2021 - Mundos das Plantas<br />
                        Rua das Plantas, nº 4A<br />
                        22000-000 Lisboa
                    </div>
                    <div class="col-12 col-md-4 text-center">
                        <a class="text-decoration-none text-white" href="https://www.livroreclamacoes.pt/inicio">Livro de reclamações</a><br />
                        <a class="text-decoration-none text-white" asp-area="" asp-controller="Home" asp-action="TrocasDevolucoes">Trocas e devoluções</a><br />
                        <a class="text-decoration-none text-white" asp-area="" asp-controller="Home" asp-action="Privacy">Política de privacidade</a>
                    </div>
                    <div class="col-12 col-md-4 text-center">
                        Precisas de ajuda? Contacte-nos:<br />
                        Email - <a class="text-decoration-none text-white-50" href="mailto:email@dominio.com">contacto@mundodasplantas.com</a><br />
                        Telefone - <a class="text-decoration-none text-white-50" href="phone:212222000">212 222 000</a><br />
                    </div>
                </div>
            </div>
        </footer>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>